# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'''
syntax = "proto3";

message MapInfo {
  string MapCode = 1;
  string MapTitle = 2;
  string description = 3;
}
''')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_info_pb2', globals())

if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _MAPINFO._serialized_start = 34
    _MAPINFO._serialized_end = 101