# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_info.proto

import sys
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

# Fix: Properly encode the serialized_pb as bytes
_b = lambda x: x.encode('latin1')

DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_info.proto',
  package='crafland',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b(
    '\n\x0emap_info.proto\x12\x08crafland\"G\n\x07MapInfo\x12\x11\n\tmap_code\x18\x01 \x01(\t\x12\x12\n\nmap_title\x18\x02 \x01(\t\x12\x13\n\x0bdescription\x18\x03 \x01(\tb\x06proto3'
  )
)

_MAPINFO = _descriptor.Descriptor(
  name='MapInfo',
  full_name='crafland.MapInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_code', full_name='crafland.MapInfo.map_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None),
    _descriptor.FieldDescriptor(
      name='map_title', full_name='crafland.MapInfo.map_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='crafland.MapInfo.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
)

DESCRIPTOR.message_types_by_name['MapInfo'] = _MAPINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapInfo = _reflection.GeneratedProtocolMessageType('MapInfo', (_message.Message,), {
  'DESCRIPTOR' : _MAPINFO,
  '__module__' : 'map_info_pb2'
})
_sym_db.RegisterMessage(MapInfo)
